version: "3.8" #도커 컴포즈 구문 버전
services: #실행할 컨테이너를 나열하는 섹션

  catalog-service: #catalog-service 컨테이너를 기술하는 섹션
    depends_on:
      - polar-postgres
    image: "catalog-service" #catalog-service 컨테이너를 실행하는데 사용할 이미지
    container_name: "catalog-service" #컨테이너 이름
    ports: #포트 매핑
      - 9001:9001
    environment: #환경변수를 나열하는 섹션
      - BPL_JVM_THREAD_COUNT=50 #메모리 계산을 위한 스레드 수를 설정하는 패키토 빌드팩 환경변수
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata #testdata 프로필 활성화

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
